spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xmlagent?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: XML
    password: XMLSecureMYSQL!
    initialization-mode: always
    continue-on-error: "true"
  datasourse:
    data: /resources/data.sql
  jpa:
    hibernate:
      show_sql: "true"
      format-sql: "true"
      ddl-auto: update
      jdbc:
        batch_size: "50"
      connection:
        CharSet: utf8
        characterEncoding: utf8
        useUnicode: "true"
server:
  error:
    whitelabel:
      enabled: "false"
  port: "8080"

sping:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
