version: '3'
services:
  mysql-standalone:
    image: mysql:8.0
    container_name: mysql-standalone
    # restart: always
    environment:
      MYSQL_DATABASE: 'xmlagent'
      MYSQL_USER: 'root'
      #MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '6603:3306'
    expose:
      - '3306'

  eureka:
    image: eureka
    container_name: eureka
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - eureka
    links:
      - eureka:eureka

  auth:
    image: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081"
    depends_on:
      - eureka
    links:
      - eureka:eureka
      - mysql-standalone:mysql


