version: '3'
services:


  gateway:
    image: gateway
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


  agent:
    image: agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "2222"
    depends_on:
      - gateway
    links:
      - gateway:gateway

  auth:
    image: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "2222"
    depends_on:
      - gateway
    links:
      - gateway:gateway
