version: '3'
services:
  mysql-standalone:
    image: mysql:8.0
    container_name: mysql-standalone
    # restart: always
    environment:
      MYSQL_DATABASE: 'xmlagent'
      MYSQL_USER: 'root'
      #MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '6603:3306'
    expose:
      - '3306'

  eureka:
    image: eureka
    container_name: eureka
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - eureka
    links:
      - eureka:eureka

  auth:
    image: auth
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081"
    depends_on:
      - eureka
    links:
      - eureka:eureka
      - mysql-standalone:mysql

  agent:
    image: agent
    container_name: agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8079"
    depends_on:
      - eureka
    links:
      - eureka:eureka

  search:
    image: search
    container_name: search
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8147"
    depends_on:
      - eureka
    links:
      - eureka:eureka

  rating:
    image: rating
    container_name: rating
    build:
      context: ./rating
      dockerfile: Dockerfile
    ports:
      - "8084"
    depends_on:
      - eureka
    links:
      - eureka:eureka


  model:
    image: model
    container_name: model
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - eureka
    links:
      - eureka:eureka

  reservation:
    image: reservation
    container_name: reservation
    build:
      context: ./reservation
      dockerfile: Dockerfile
    ports:
      - "8888"
    depends_on:
      - eureka
    links:
      - eureka:eureka


