//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 02:37:11 AM CEST 
//


package com.megatravel.models.agent;

import com.megatravel.dtos.agent.AccommodationTypeDTO;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



@SuppressWarnings("WeakerAccess")
@Entity
public class AccommodationType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    protected String nameOfAccType;

    public AccommodationType() {
        super();
    }

    public AccommodationType(AccommodationTypeDTO accommodationTypeDTO) {
        this.id = accommodationTypeDTO.getId();
        this.nameOfAccType = accommodationTypeDTO.getNameOfAccType();
    }



    public AccommodationType(String nameOfAccType) {
        this.nameOfAccType = nameOfAccType;
    }

    public long getId() {
        return id;
    }


    public void setId(long value) {
        this.id = value;
    }

    public String getNameOfAccType() {
        return nameOfAccType;
    }

    public void setNameOfAccType(String value) {
        this.nameOfAccType = value;
    }

}
