//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 02:37:11 AM CEST 
//


package com.megatravel.models.agent;


import com.megatravel.dtos.agent.AccommodationDTO;
import com.megatravel.models.admin.User;
import com.megatravel.models.types.Location;

import javax.persistence.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@SuppressWarnings("WeakerAccess")
public class Accommodation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    protected String name;

    protected String description;

    @ManyToOne
    protected Location location;

    @ManyToOne
    protected AccommodationType accommodationType;

    @OneToOne
    protected User user; // User that administrates the accommodation

    @OneToMany(mappedBy = "accommodation")
    protected List<AccommodationUnit> accommodationUnit = new ArrayList<>();

    @ManyToMany
    protected List<ExtraService> extraService = new ArrayList<>();


    protected Date lastChangedDate;

    public Accommodation() {
        this.lastChangedDate = new Date();
    }

    public Accommodation(AccommodationDTO accommodationDTO) {
        this.id = accommodationDTO.getId();
        this.name = accommodationDTO.getName();
        this.description = accommodationDTO.getDescription();
        this.location = new Location(accommodationDTO.getLocationDTO());
        this.lastChangedDate = accommodationDTO.getLastChangedDate();
    }

    public Date getLastChangedDate() {
        return lastChangedDate;
    }

    public void setLastChangedDate(Date lastChangedDate) {
        this.lastChangedDate = lastChangedDate;
    }

    public long getId() {
        return id;
    }


    public void setId(long value) {
        this.id = value;
    }


    public String getName() {
        return name;
    }


    public void setName(String value) {
        this.name = value;
    }


    public String getDescription() {
        return description;
    }


    public void setDescription(String value) {
        this.description = value;
    }


    public Location getLocation() {
        return location;
    }


    public void setLocation(Location value) {
        this.location = value;
    }


    public AccommodationType getAccommodationType() {
        return accommodationType;
    }


    public void setAccommodationType(AccommodationType value) {
        this.accommodationType = value;
    }


    public User getUser() {
        return user;
    }


    public void setUser(User value) {
        this.user = value;
    }


    public void setAccommodationUnit(List<AccommodationUnit> accommodationUnit) {
        this.accommodationUnit = accommodationUnit;
    }

    public void setExtraService(List<ExtraService> extraService) {
        this.extraService = extraService;
    }


    public List<AccommodationUnit> getAccommodationUnit() {
        if (accommodationUnit == null) {
            accommodationUnit = new ArrayList<AccommodationUnit>();
        }
        return this.accommodationUnit;
    }


    public List<ExtraService> getExtraService() {
        if (extraService == null) {
            extraService = new ArrayList<ExtraService>();
        }
        return this.extraService;
    }



}
