//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 02:37:11 AM CEST 
//


package com.megatravel.models.agent;

import com.megatravel.dtos.agent.PricingDTO;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;


@SuppressWarnings("WeakerAccess")
@Entity
public class Pricing {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    protected BigDecimal price;

    protected Date startDate;

    @ManyToOne
    protected AccommodationUnit priceForUnit;

    protected Date lastChangedDate;

    public Pricing() {
        this.lastChangedDate = new Date();
    }

    public Pricing(PricingDTO pricingDTO) {
        this.id = pricingDTO.getId();
        this.price = pricingDTO.getPrice();
        this.startDate = pricingDTO.getStartDate();
        this.lastChangedDate = pricingDTO.getLastChangedDate();
    }


    public Pricing(long id, BigDecimal price, Date startDate) {
        this.id = id;
        this.price = price;
        this.startDate = startDate;
    }

    public AccommodationUnit getPriceForUnit() {
        return priceForUnit;
    }

    public void setPriceForUnit(AccommodationUnit priceForUnit) {
        this.priceForUnit = priceForUnit;
    }

    public long getId() {
        return id;
    }


    public void setId(long value) {
        this.id = value;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date value) {
        this.startDate = value;
    }

    public Date getLastChangedDate() {
        return lastChangedDate;
    }

    public void setLastChangedDate(Date lastChangedDate) {
        this.lastChangedDate = lastChangedDate;
    }
}
