//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 02:37:11 AM CEST 
//


package com.megatravel.models.agent;

import com.megatravel.dtos.agent.UnitTypeDTO;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@SuppressWarnings("WeakerAccess")
@Entity
public class UnitType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;
    protected String nameOfUnitType;

    public UnitType() {
    }

    public UnitType(UnitTypeDTO unitTypeDTO){
        this.id = unitTypeDTO.getId();
        this.nameOfUnitType = unitTypeDTO.getNameOfUnitType();
    }

    public UnitType(String nameOfUnitType) {
        this.nameOfUnitType = nameOfUnitType;
    }

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getNameOfUnitType() {
        return nameOfUnitType;
    }

    public void setNameOfUnitType(String value) {
        this.nameOfUnitType = value;
    }

}
