spring:
  application:
    name: gateway
server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  ignoredServices: auth, agent, message, search, rating, reservation
  prefix:  /api
  host:
    socket-timeout-millis: 40000
  routes:
    auth: /auth/**
    agent: /login/**
    search: /search/**
    rating: /rating/**
    message: /message/**
    reservation: /reservation/**


