spring:
  application:
    name: gateway
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth
    agent:
      path: /agent/**
      serviceId: agent
    message:
      path: /msg/**
      serviceId: message
    rating:
      path: /rating/**
      serviceId: rating
    reservation:
      path: /reservation/**
      serviceId: reservation
    search:
      path: /search/**
      serviceId: search



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#
#zuul:
#  routes:
#    containerized-main:
#      path: /service1/**
#      serviceId: containerized-service1
#    containerized-accounts:
#      path: /service2/**
#      serviceId: containerized-service2
