spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xmlagent?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: XML
    password: XMLSecureMYSQL!
    initialization-mode: always
    continue-on-error: "true"
  datasourse:
    data: /resources/data.sql
  jpa:
    hibernate:
      show_sql: "true"
      format_sql: "true"
      ddl-auto: update
      jdbc:
        batch_size: "50"
      connection:
        CharSet: utf8
        characterEncoding: utf8
        useUnicode: "true"
server:
  error:
    whitelabel:
      enabled: "false"
  port: "8081"
#  ssl:
#    enabled: "true"
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12

# A more restrictive one
#  ssl:
#        key-store: classpath:config/tls/keystore.p12
#        key-store-password: password
#        key-store-type: PKCS12
#        key-alias: megatravel
#        ciphers: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
#        enabled-protocols: TLSv1.2
#  http2:
#       enabled: true
sping:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
