spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xmlagent?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: XML
    password: XMLSecureMYSQL!
    initialization-mode: always
    continue-on-error: "true"
  datasourse:
    data: /resources/data.sql
  jpa:
    hibernate:
      show_sql: "true"
      format_sql: "true"
      ddl-auto: update
      jdbc:
        batch_size: "50"
      connection:
        CharSet: utf8
        characterEncoding: utf8
        useUnicode: "true"
  application:
    name: Reservation
server:
  error:
    whitelabel:
      enabled: "false"
  port: 0 #"8082" previously, now randomly
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
sping:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
