
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xmlagent?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: XML
    password: XMLSecureMYSQL!
    initialization-mode: always
    continue-on-error: "true"
  datasourse:
    data: /resources/data.sql
  jpa:
    hibernate:
      show_sql: "true"
      format_sql: "true"
      ddl-auto: update
      jdbc:
        batch_size: "50"
      connection:
        CharSet: utf8
        characterEncoding: utf8
        useUnicode: "true"
  application:
    name: message


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  error:
    whitelabel:
      enabled: "false"
  port: 8888 #"8084"

sping:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

#eureka:
#  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
