//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.06.22 at 05:53:12 PM CEST
//


package com.megatravel.models.agent;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

@Entity
public class SyncData {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    protected Date dateOfSync;

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public Date getDateOfSync() {
        return dateOfSync;
    }

    public void setDateOfSync(Date value) {
        this.dateOfSync = value;
    }

}
