//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.04 at 07:10:31 PM CEST 
//


package com.megatravel.interfaces;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://interfaces.megatravel.com/}messageDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageDTO"
})
@XmlRootElement(name = "SendMessageResponse")
public class SendMessageResponse {

    protected MessageDTO messageDTO;

    /**
     * Gets the value of the messageDTO property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDTO }
     *     
     */
    public MessageDTO getMessageDTO() {
        return messageDTO;
    }

    /**
     * Sets the value of the messageDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDTO }
     *     
     */
    public void setMessageDTO(MessageDTO value) {
        this.messageDTO = value;
    }

}
