//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.31 at 10:45:46 PM CEST 
//


package com.megatravel.interfaces;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.interfaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.interfaces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocationDTO }
     * 
     */
    public LocationDTO createLocationDTO() {
        return new LocationDTO();
    }

    /**
     * Create an instance of {@link GetAllAccType }
     * 
     */
    public GetAllAccType createGetAllAccType() {
        return new GetAllAccType();
    }

    /**
     * Create an instance of {@link GetAllAccTypeResponse }
     * 
     */
    public GetAllAccTypeResponse createGetAllAccTypeResponse() {
        return new GetAllAccTypeResponse();
    }

    /**
     * Create an instance of {@link AccommodationTypeDTO }
     * 
     */
    public AccommodationTypeDTO createAccommodationTypeDTO() {
        return new AccommodationTypeDTO();
    }

    /**
     * Create an instance of {@link AccommodationUnitDTO }
     * 
     */
    public AccommodationUnitDTO createAccommodationUnitDTO() {
        return new AccommodationUnitDTO();
    }

    /**
     * Create an instance of {@link UnitTypeDTO }
     * 
     */
    public UnitTypeDTO createUnitTypeDTO() {
        return new UnitTypeDTO();
    }

    /**
     * Create an instance of {@link PricingDTO }
     * 
     */
    public PricingDTO createPricingDTO() {
        return new PricingDTO();
    }

    /**
     * Create an instance of {@link ExtraServiceDTO }
     * 
     */
    public ExtraServiceDTO createExtraServiceDTO() {
        return new ExtraServiceDTO();
    }

    /**
     * Create an instance of {@link AccommodationDTO }
     * 
     */
    public AccommodationDTO createAccommodationDTO() {
        return new AccommodationDTO();
    }

    /**
     * Create an instance of {@link UserDTO }
     * 
     */
    public UserDTO createUserDTO() {
        return new UserDTO();
    }

    /**
     * Create an instance of {@link RoleDTO }
     * 
     */
    public RoleDTO createRoleDTO() {
        return new RoleDTO();
    }

    /**
     * Create an instance of {@link ImageDTO }
     * 
     */
    public ImageDTO createImageDTO() {
        return new ImageDTO();
    }

    /**
     * Create an instance of {@link GetChatRoomsResponse }
     * 
     */
    public GetChatRoomsResponse createGetChatRoomsResponse() {
        return new GetChatRoomsResponse();
    }

    /**
     * Create an instance of {@link ChatRoomDTO }
     * 
     */
    public ChatRoomDTO createChatRoomDTO() {
        return new ChatRoomDTO();
    }

    /**
     * Create an instance of {@link ReservationDTO }
     * 
     */
    public ReservationDTO createReservationDTO() {
        return new ReservationDTO();
    }

    /**
     * Create an instance of {@link RatingDTO }
     * 
     */
    public RatingDTO createRatingDTO() {
        return new RatingDTO();
    }

    /**
     * Create an instance of {@link GetAllAccommodations }
     * 
     */
    public GetAllAccommodations createGetAllAccommodations() {
        return new GetAllAccommodations();
    }

    /**
     * Create an instance of {@link CreateAccType }
     * 
     */
    public CreateAccType createCreateAccType() {
        return new CreateAccType();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link MessageDTO }
     * 
     */
    public MessageDTO createMessageDTO() {
        return new MessageDTO();
    }

    /**
     * Create an instance of {@link GetListMessagesForChatRoomResponse }
     * 
     */
    public GetListMessagesForChatRoomResponse createGetListMessagesForChatRoomResponse() {
        return new GetListMessagesForChatRoomResponse();
    }

    /**
     * Create an instance of {@link CreateAccTypeResponse }
     * 
     */
    public CreateAccTypeResponse createCreateAccTypeResponse() {
        return new CreateAccTypeResponse();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link SendMessage }
     * 
     */
    public SendMessage createSendMessage() {
        return new SendMessage();
    }

    /**
     * Create an instance of {@link ConfirmReservationResponse }
     * 
     */
    public ConfirmReservationResponse createConfirmReservationResponse() {
        return new ConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link GetAccType }
     * 
     */
    public GetAccType createGetAccType() {
        return new GetAccType();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetAllAccommodationsResponse }
     * 
     */
    public GetAllAccommodationsResponse createGetAllAccommodationsResponse() {
        return new GetAllAccommodationsResponse();
    }

    /**
     * Create an instance of {@link GetAccTypeResponse }
     * 
     */
    public GetAccTypeResponse createGetAccTypeResponse() {
        return new GetAccTypeResponse();
    }

    /**
     * Create an instance of {@link CreateReservation }
     * 
     */
    public CreateReservation createCreateReservation() {
        return new CreateReservation();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginDTO }
     * 
     */
    public LoginDTO createLoginDTO() {
        return new LoginDTO();
    }

    /**
     * Create an instance of {@link ConfirmReservation }
     * 
     */
    public ConfirmReservation createConfirmReservation() {
        return new ConfirmReservation();
    }

    /**
     * Create an instance of {@link GetAccommodation }
     * 
     */
    public GetAccommodation createGetAccommodation() {
        return new GetAccommodation();
    }

    /**
     * Create an instance of {@link GetListMessagesForChatRoom }
     * 
     */
    public GetListMessagesForChatRoom createGetListMessagesForChatRoom() {
        return new GetListMessagesForChatRoom();
    }

    /**
     * Create an instance of {@link GetListReservationsForAgent }
     * 
     */
    public GetListReservationsForAgent createGetListReservationsForAgent() {
        return new GetListReservationsForAgent();
    }

    /**
     * Create an instance of {@link GetChatRooms }
     * 
     */
    public GetChatRooms createGetChatRooms() {
        return new GetChatRooms();
    }

    /**
     * Create an instance of {@link RegistrationDTO }
     * 
     */
    public RegistrationDTO createRegistrationDTO() {
        return new RegistrationDTO();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetListReservationsForAgentResponse }
     * 
     */
    public GetListReservationsForAgentResponse createGetListReservationsForAgentResponse() {
        return new GetListReservationsForAgentResponse();
    }

}
